### PR TITLE
Added support for any type of channel.

### PR DESCRIPTION
**Pull request by casskir**
Added support for any type of channel.

### CODE REVIEW

**Comment by ahmetb** [comment]
Can you remind me what's the current limitation?
Also we'll likely need some tests if there's behavioral change.

**Comment by casskir** [comment]
> Can you remind me what's the current limitation?

We can't use the typed channel with linq package.
Before:

```
origCh := make(chan int)
srcCh := make(chan interface{})

// Forward
go func() {
    for {
        srcCh <- origCh
    }
}()

From(srcCh)...
```

Now:

```
origCh := make(chan int)
From(origCh)...
```

> Also we'll likely need some tests if there's behavioral change.

I'm not sure about additional tests because logic was not changed. The old test is good for these changes.

**Comment by ahmetb** [comment]
I think at least we can change tests to be `chan int` instead of `chan interface{}` to verify that it indeed works the way you wanted.

**Comment by casskir** [comment]
Agreed. I changed from `chan interface{}` to `chan int`.

**Comment by kalaninja** [comment]
@casskir I am generally ok with this idea, though since you use reflection to receive from the channel I expect the performance of this method to be worse. So, it would probably be better to introduce a new method, say, `FromTypedChannel()`.

I did a benchmark
```
BenchmarkFromChannel-12                  	      10	 189264414 ns/op
BenchmarkFromTypedChannel-12             	       3	 758983592 ns/op
```

And I did a pr #90 with the new method.
@casskir @ahmetb what do you think?

**Comment by casskir** [comment]
I think it more flexible, especially in case if performance is important. @ahmetb please close pr #89 if you agree.

**Comment by ahmetb** [comment]
Yeah #90 is preferable, since we have a generic worse-performing `From` for syntactic sugar and `FromXxx` for less-guesswork and therefore better performance.

Thanks a lot for this patch though. Make sure #90 addresses your problem.

**Pull request closed without merging**
