### PR TITLE
Fix username in README.md

### PR DESCRIPTION
**Pull request by ahmetb**

### CODE REVIEW

**Comment by kalaninja** [comment]
@ahmetb fix coveralls, please

**Comment by ahmetb** [comment]
I already updated those. Just to be clear, things that still will work with old repo URL:

- `go get`  (will actually clone repo with its old name)
- visiting old repo URL on github (redirects)
- git push to the old remote URL

so not many things are on fire right now. Updated readme so that new users use the right URL, plus travis badge image was broken.

**Comment by ahmetb** [comment]
@kalaninja so it looks like I enabled coveralls again, however no results show up yet (maybe because there are no builds since I enabled), but `goveralls` upload command doesn't fail so I assume the repo token is correct. If it doesn't work I will attempt to fix it.

**Comment by ahmetb** [comment]
Looks like coveralls is back, we're good. 👍

**Pull request merged**
