### PR TITLE
added left join support

### PR DESCRIPTION
**Pull request by alexbumbacea**

### CODE REVIEW

**Comment by cleitonmarx** [comment]
Hey @alexbumbacea, Thanks for your PR!

Here is an example of how a [left outer join is written using C#](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins) and below is the exactly same example but written in go using go-linq:
```go 
type Person struct {
    FirstName string
    LastName  string
}

type Pet struct {
    Name  string
    Owner Person
}

type PersonPets struct {
    Person Person
    Pets   []Pet
}

magnus := Person{FirstName: "Magnus", LastName: "Hedlund"}
terry := Person{FirstName: "Terry", LastName: "Adams"}
charlotte := Person{FirstName: "Charlotte", LastName: "Weiss"}
arlene := Person{FirstName: "Arlene", LastName: "Huff"}

barley := Pet{Name: "Barley", Owner: terry}
boots := Pet{Name: "Boots", Owner: terry}
whiskers := Pet{Name: "Whiskers", Owner: charlotte}
bluemoon := Pet{Name: "Blue Moon", Owner: terry}
daisy := Pet{Name: "Daisy", Owner: magnus}

// Create two lists.
people := []Person{magnus, terry, charlotte, arlene}
pets := []Pet{barley, boots, whiskers, bluemoon, daisy}

results := []string{}
linq.From(people).
    GroupJoinT(
        linq.From(pets),
        func(person interface{}) interface{} { return person },
        func(pet interface{}) interface{} { return pet.(Pet).Owner },
        func(person interface{}, pets []interface{}) interface{} { return linq.Group{Key: person, Group: pets} },
    ).
    SelectManyBy(
        func(g interface{}) linq.Query {
            if len(g.(linq.Group).Group) > 0 {
                return linq.From(g.(linq.Group).Group)
            }
            return linq.From([]Pet{{}})
        },
        func(pet, group interface{}) interface{} {
            return fmt.Sprintf("%s: %s", group.(linq.Group).Key.(Person).FirstName, pet.(Pet).Name)
        },
    ).
    ToSlice(&results)

for _, s := range results {
    fmt.Println(s)
}
```
Something that I missed in go-linq while I was writing this example was the function [DefaultIfEmpty](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/DefaultIfEmpty.cs). This function could replace the logic inside the `SelectManyBy`selector function:
```go
SelectManyBy(
        func(g interface{}) linq.Query { return linq.From(g.(linq.Group).Group).DefaultIfEmpty()},
        func(pet, group interface{}) interface{} {
            return fmt.Sprintf("%s: %s", group.(linq.Group).Key.(Person).FirstName, i.(Pet).Name)
        },
    )
```
I would suggest you the implementation of the `DefaultIfEmpty` function as a new PR since this library is based on the .NET linq and it's useful to handle left outer joins. What do you think @ahmetb and @kalaninja ?

**Comment by ahmetb** [comment]
I'll try to take a look at this after Nov 26, you don't need to wait for me. It's going to be a huge context switch for me to understand the problem and the solution after many years not iterating on the repo.

**Comment by alexbumbacea** [comment]
Hello @ahmetb, Have you had the chance to look into this? Thanks

**Comment by ahmetb** [comment]
Ah I got super busy, don't expect anything from me for another two weeks. @cleitonmarx’s review would be more instrumental here.

**Comment by alexbumbacea** [comment]
Hello @ahmetb ,

Any updates on this?

**Comment by ahmetb** [comment]
Sorry for the radio silence here. I've long forgotten our codebase. :(

If @cleitonmarx says we should have this method, and it mirrors .NET LINQ behavior, I'd be happy to accept his review/decision. If not, we should just close.

**Comment by cleitonmarx** [comment]
I'm closing this PR since it's possible to have the same results using `GroupJoin` + `SelectManyBy`. Soon I'll send the PR with the `DefaultIfEmpty` implementation

**Pull request closed without merging**
